### ISSUE TITLE
callerhistory yaml complete?

### ISSUE THREAD

**Issue by m66rus** [amazon-connect/amazon-connect-snippets#49]
I was just looking at the yaml file for this feature and notice the creation of the table does not look complete with all the attributes for the table. Has something been missed or is it suppose to just define one attribute?

**Comment by mcosicaws** [comment]
Amazon DynamoDB is a NoSQL (key-value and document) database, and it does not require a definition of all attributes. Basically, it only requires an array of attributes that describe the key schema for the table and indexes. 
More information can be found here: 
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html 

In this particular case, `ContactId` is defined as `PrimaryKey`, while all other attributes are defined in PUT/UPDATE commands, directly in Lambda function. 

I hope this help, but please re-open should you need any additional details.

Thanks
Milos
