### ISSUE TITLE
Issue when associating assistant and KB to Connect instance.

### ISSUE THREAD

**Issue by david-macias** [amazon-connect/amazon-connect-snippets#88]
Following along with this blog (https://aws.amazon.com/blogs/contact-center/ingesting-content-to-power-real-time-recommendations-and-search-with-amazon-connect-wisdom/), when it's time to associate the assistant and KB it yields the following error:

"An error occurred (InvalidRequestException) when calling the CreateIntegrationAssociation operation: Reached Integration association limit for the Amazon Connect instance."

I don't see where this limit is set and can be increased. Seems like I'm not the only one who has had the issue (https://repost.aws/questions/QUMKJhNx-QQaGpt6nznuJEAg/how-i-can-increase-the-integration-association-limit-for-the-amazon-connect-instance)

**Comment by virtualgill** [comment]
There are a number of service quotas for different integrations that you can see here: https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-service-limits.html
Some of these can be adjusted. Some cannot.

Try running [ListIntegrationAssociations](https://docs.aws.amazon.com/connect/latest/APIReference/API_ListIntegrationAssociations.html) to see your current integration associations and if any of them are hitting the limits in the docs.

**Comment by david-macias** [comment]
Yeah you're on the right track. Through the UI I added a domain and that's what caused the issue. Once I removed that and did everything via the CLI first things worked. Thank you!
