### ISSUE TITLE
Skew Metrics Local Time

### ISSUE THREAD

**Issue by lwang-79** [amazon-connect/amazon-connect-snippets#94]
Hi team,

I think there is a bug in the skew metrics tooltip. The `Server Time` should be `Local Time` and `Local Time` should be `Server Time`. Shouldn't 14:21:18 be behind 14:21:57? Please check.
![Screenshot 2023-05-26 at 9 59 58 am](https://github.com/amazon-connect/amazon-connect-snippets/assets/80386004/ab21936e-8db9-4f7b-9526-9d6216036203)

**Comment by virtualgill** [comment]
Thanks for your report. I checked with the team and they verified that the ServerTime / LocalTime are correct, however the tooltip message does create confusion. An item to adjust the tooltip has been added to the backlog.
